AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'production' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non numberic character.
Resources:
  RECIPES:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "user_users-${EnvName}"
      AttributeDefinitions:
      -
        AttributeName: "email"
        AttributeType: "S"
      -
        AttributeName: "id"
        AttributeType: "S"
      KeySchema:
      -
        AttributeName: "email"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      GlobalSecondaryIndexes:
      -
        IndexName: "id-index"
        KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
